name: teta_dbt_project
version: 1.0.0
config-version: 2

profile: clickhouse

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: []
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: view
  staging:
    +materialized: view
  marts:
    +materialized: table
